version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: x64
init:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
install:
    - set QTDIR=C:\Qt\5.10.1\msvc2017_64
    - set PATH=%PATH%;%QTDIR%\bin
build_script:
    - qmake GCodeViz.pro
    - nmake